remote_theme: pmarsceill/just-the-docs

title: White Rabbit
description: White Rabbit and Rabbit in a Hat documentation

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Source code":
    - "//github.com/ohdsi/WhiteRabbit"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

footer_content: "White Rabbit v0.9.0 | Copyright &copy; Observational Health Data Sciences and Informatics & The Hyve</a>"